numpy:
  - 2.*
  - 2.*
  - 2.*
python:
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cp313
python_min:
  - 3.11
is_python_min:
  - true
  - false
  - false
python_impl:
  - cpython
  - cpython
  - cp313
