{% set name = "piconnect" %}
{% set version = "0.12.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dfd47579fcb214160e1bb88a76a88bb8609c65789f8af2f3419b4c134b363076

build:
  number: 0
  skip: true  # [not win]
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=2,<3
    - pandas >=2,<3
    - python
    - pythonnet >=3
    - wrapt >=1.17,<2

test:
  imports:
    - PIconnect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Hugovdberg/PIconnect
  summary: Python connector to OSIsoft PI SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Hugovdberg
