context:
  version: 0.12.4
  python_min: 3.11

package:
  name: piconnect
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/piconnect/piconnect-${{ version }}.tar.gz
  sha256: a9498321b07df3a964a336c49239fa67b85b36a66c563a9d6fd576306549cfc4

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ==${{ python_min }}
    - setuptools >=75.0
    - versioneer >=0.28
    - pip
  run:
    - python >=${{ python_min }}
    - pandas <3,>=2
    - numpy <3,>=2
    - pythonnet >=3
    - wrapt <2,>=1.17

tests:
  - python:
      imports:
        - PIconnect
      pip_check: true

about:
  homepage: https://github.com/Hugovdberg/PIconnect
  summary: PIconnect - Connector to the OSISoft PI and PI-AF databases.
  license: MIT
  license_file: LICENSE
  description: "#########\r\nPIconnect\r\n#########\r\n\r\nA python connector to the OSISoft PI and PI-AF databases\r\n========================================================\r\n\r\nThis connector allows access to the OSISoft PI System through their\r\nproprietary SDK. It provides a number of classes, mostly mirroring the AF SDK\r\nstructure, but at the same time implementing the cool stuff we use Python for.\r\nConnections to the database are therefore implemented as context managers, to\r\nallow opening a connection using a with statement.\r\n\r\n.. image:: https://img.shields.io/pypi/v/PIconnect.svg\r\n    :target: https://pypi.python.org/pypi/PIconnect\r\n    :alt: PIconnect on PyPI\r\n\r\n.. image:: https://img.shields.io/conda/vn/conda-forge/piconnect\r\n    :target: https://anaconda.org/conda-forge/piconnect\r\n    :alt: PIconnect on conda-forge\r\n\r\n.. image:: https://github.com/Hugovdberg/PIconnect/actions/workflows/ci.yml/badge.svg?branch=develop\r\n    :target: https://github.com/Hugovdberg/PIconnect/actions/workflows/ci.yml\r\n    :alt: Continuous Integration status\r\n\r\n.. image:: https://readthedocs.org/projects/piconnect/badge/?version=develop\r\n    :target: https://piconnect.readthedocs.io/en/latest/?badge=develop\r\n    :alt: Documentation Status\r\n\r\n.. image:: https://pyup.io/repos/github/Hugovdberg/PIconnect/shield.svg\r\n    :target: https://pyup.io/repos/github/Hugovdberg/PIconnect/\r\n    :alt: Security Updates\r\n\r\n.. image:: https://api.codacy.com/project/badge/Grade/568734c85e07467c99e0e791d8eb17b6\r\n    :target: https://www.codacy.com/app/Hugovdberg/PIconnect?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=Hugovdberg/PIconnect&amp;utm_campaign=Badge_Grade\r\n    :alt: Automated code review\r\n\r\n.. image:: https://img.shields.io/badge/code%20style-black-000000.svg\r\n    :target: https://github.com/psf/black\r\n    :alt: Code style: black\r\n\r\nPython connector to OSIsoft PI SDK\r\n\r\n\r\n* Free software: MIT license\r\n* Documentation: https://piconnect.readthedocs.io.\r\n\r\n\r\nFeatures\r\n--------\r\nFeatures below are for both: PI Server and PIAF Database:\r\n\r\n* Extract recorded values\r\n* Extract interpolated values\r\n* Update a value\r\n* Summarize data before extraction with help of OSIsoft PI SDK\r\n* Filter data before extraction with help of OSIsoft PI SDK\r\n\r\nCopyright notice\r\n================\r\nOSIsoft, the OSIsoft logo and logotype, Managed PI, OSIsoft Advanced Services,\r\nOSIsoft Cloud Services, OSIsoft Connected Services, PI ACE, PI Advanced\r\nComputing Engine, PI AF SDK, PI API, PI Asset Framework, PI Audit Viewer, PI\r\nBuilder, PI Cloud Connect, PI Connectors, PI Data Archive, PI DataLink, PI\r\nDataLink Server, PI Developer's Club, PI Integrator for Business Analytics, PI\r\nInterfaces, PI JDBC driver, PI Manual Logger, PI Notifications, PI ODBC, PI\r\nOLEDB Enterprise, PI OLEDB Provider, PI OPC HDA Server, PI ProcessBook, PI\r\nSDK, PI Server, PI Square, PI System, PI System Access, PI Vision, PI\r\nVisualization Suite, PI Web API, PI WebParts, PI Web Services, RLINK and\r\nRtReports are all trademarks of OSIsoft, LLC.\r\n\r\nCredits\r\n---------\r\n\r\nThis package was created with Cookiecutter_ and the\r\n`audreyr/cookiecutter-pypackage`_ project template.\r\n\r\n.. _Cookiecutter: https://github.com/audreyr/cookiecutter\r\n.. _`audreyr/cookiecutter-pypackage`: https://github.com/audreyr/cookiecutter-pypackage\r\n"
  documentation: https://piconnect.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - Hugovdberg
