azure:
  settings_win:
    pool:
      vmImage: windows-2019
bot:
  automerge: true
  inspection: update-all
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
